declare namespace Cloudflare {
 interface Env {DB?:D1Database; SMTP_ADAPTER_URL?:string; SMTP_ADAPTER_TOKEN?:string; SARVAM_TRANSCRIBE_MODEL?:string; SARVAM_TTS_MODEL?:string; RECORDINGS?:R2Bucket; SARVAM_API_KEY?:string; SARVAM_TOOL_TOKEN?:string; SARVAM_DICTIONARY_ID?:string; SARVAM_VOICE?:string; SARVAM_REASONING_MODEL?:string; DESK_SERVICE_TOKEN?:string; TRANSFER_ADAPTER_URL?:string; TRANSFER_ADAPTER_TOKEN?:string; ERP_ADAPTER_URL?:string; ERP_ADAPTER_TOKEN?:string; MESSAGE_ADAPTER_URL?:string; MESSAGE_ADAPTER_TOKEN?:string;}
}
