import fs from 'node:fs';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const root=process.cwd(),require=createRequire(root+'/package.json');
const {Miniflare}=createRequire(require.resolve('wrangler/package.json'))('miniflare');
let speechInput,failSpeech=false,transcription='What is the B.Tech tuition fee?',speechCalls=0,sessionInput;
const wav='UklGRiQAAABXQVZFZm10IBAAAAABAAEAESsAACJWAAACABAAZGF0YQAAAAA=';
const outboundService=async request=>{
 const url=new URL(request.url);assert.equal(url.hostname,'api.sarvam.ai');assert.equal(request.headers.get('api-subscription-key'),'synthetic-not-a-real-key');
 if(url.pathname==='/speech-to-text'){const body=await request.formData();assert.equal(body.get('model'),'saaras:v4');assert.equal(body.get('mode'),'codemix');sessionInput=body;return Response.json({transcript:transcription});}
 if(url.pathname.startsWith('/text-to-speech')){speechCalls++;speechInput=await request.json();if(failSpeech)return new Response('Synthetic outage',{status:503});return url.pathname.endsWith('/stream')?new Response(new Uint8Array([0,0,0,128,255,127]),{headers:{'Content-Type':'audio/pcm'}}):Response.json({audios:[wav]});}
 return new Response('Unexpected synthetic provider request',{status:502});
};
const mf=new Miniflare({modulesRoot:root+'/dist/server',modules:[{type:'ESModule',path:root+'/dist/server/index.js'},...fs.readdirSync(root+'/dist/server',{recursive:true}).filter(x=>x.endsWith('.js')&&x!=='index.js').map(x=>({type:'ESModule',path:root+'/dist/server/'+x}))],compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['RECORDINGS'],bindings:{DESK_SERVICE_TOKEN:'synthetic-worker-token',SARVAM_API_KEY:'synthetic-not-a-real-key',SARVAM_TOOL_TOKEN:'synthetic-hosted-tool'},outboundService});
const headers={'oai-authenticated-user-id':'synthetic-owner','oai-authenticated-user-email':'owner@example.test'};
let n=0;const results=[];async function check(name,fn){try{await fn()}catch(e){throw new Error(name,{cause:e})}n++;results.push({name,passed:true})}
async function audioPost(form){const req=new Request('http://desk.test/api/audio',{method:'POST',body:form});return mf.dispatchFetch(req.url,{method:'POST',headers:{...headers,'Content-Type':req.headers.get('content-type')},body:await req.arrayBuffer()});}
async function post(body,extra={}){return mf.dispatchFetch('http://desk.test/api/desk',{method:'POST',headers:{...headers,'Content-Type':'application/json',...extra},body:JSON.stringify(body)});}
try{
 const db=await mf.getD1Database('DB');for(const file of fs.readdirSync(root+'/drizzle').filter(x=>x.endsWith('.sql')).sort())for(const sql of fs.readFileSync(root+'/drizzle/'+file,'utf8').split('--> statement-breakpoint').filter(x=>x.trim()))await db.prepare(sql).run();
 await check('Compiled app renders',async()=>{const r=await mf.dispatchFetch('http://desk.test/',{headers});assert.equal(r.status,200);assert.ok((await r.text()).includes('Campus Desk'))});
 await check('Unauthenticated API rejects access',async()=>assert.equal((await mf.dispatchFetch('http://desk.test/api/desk')).status,401));
 await check('Overview seeds college facts and empty HOD addresses',async()=>{const r=await mf.dispatchFetch('http://desk.test/api/desk',{headers});assert.equal(r.status,200);const d=await r.json();assert.ok(d.knowledge.length>=30);assert.equal(d.emailDirectory.length,18);assert.ok(d.emailDirectory.every(x=>!x.email))});
 await check('Cross-origin mutation rejects access',async()=>assert.equal((await post({action:'call.start'},{Origin:'https://evil.test'})).status,403));
 const call=(await (await post({action:'call.start',language:'en',channel:'voice'})).json()).id;
 await check('Compiled resolver quotes the qualified annual fee',async()=>{const r=await (await post({action:'call.say',callId:call,question:'What is B.Tech tuition fee?',language:'en'})).json();assert.equal(r.decision,'answer');assert.ok(r.reply.includes('₹1,40,000'));assert.equal(r.sources[0].url,'https://vardhaman.org/programmes/')});
 await check('Disabled premium audio returns a configuration error',async()=>assert.equal((await mf.dispatchFetch('http://desk.test/api/audio',{method:'POST',headers})).status,503));
 await post({action:'config.save',collegeName:'Vardhaman College of Engineering',retentionDays:30,voiceEnabled:true,recordingEnabled:false});
 await check('Hosted tool rejects staff headers without its scoped credential',async()=>{const r=await mf.dispatchFetch('http://desk.test/api/sarvam/tools',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({operation:'start',interactionId:'http-agent'})});assert.equal(r.status,401);});
 await check('Hosted hook authenticates, starts once and refuses arbitrary actions',async()=>{const invoke=body=>mf.dispatchFetch('http://desk.test/api/sarvam/tools',{method:'POST',headers:{Authorization:'Bearer synthetic-hosted-tool','Content-Type':'application/json'},body:JSON.stringify(body)});for(let n=0;n<2;n++)assert.equal((await invoke({operation:'start',interactionId:'http-agent'})).status,200);assert.equal((await invoke({operation:'email.send',interactionId:'http-agent'})).status,400);assert.equal((await invoke({operation:'end',interactionId:'http-agent'})).status,200);assert.equal((await invoke({operation:'resolve',interactionId:'http-agent',question:'CSE HOD'})).status,409);});
 await check('Premium chain passes the exact approved answer to speech',async()=>{const f=new FormData();f.set('callId',call);f.set('language','en');f.set('audio',new Blob(['synthetic '.repeat(40)],{type:'audio/webm'}),'turn.webm');const r=await audioPost(f);assert.equal(r.status,200,await r.clone().text());const d=await r.json();assert.equal(d.result.decision,'answer');assert.ok(d.result.reply.includes('₹1,40,000'));assert.ok(d.audio,JSON.stringify(d));assert.equal(d.audio,wav);const sent=speechInput;assert.equal(sent.text,d.result.reply);assert.equal(sent.speaker,'ritu')});
 await check('Speech outage still returns the verified answer',async()=>{failSpeech=true;const f=new FormData();f.set('callId',call);f.set('language','en');f.set('audio',new Blob(['synthetic '.repeat(40)],{type:'audio/webm'}),'turn.webm');const r=await audioPost(f);assert.equal(r.status,200);const d=await r.json();assert.equal(d.audio,null);assert.ok(d.result.reply.includes('₹1,40,000'));assert.ok(d.audioError)});
 await check('Invalid audio format is rejected',async()=>{const f=new FormData();f.set('callId',call);f.set('audio',new Blob(['text '.repeat(100)],{type:'text/plain'}),'bad.txt');assert.equal((await audioPost(f)).status,400)});
 await check('Email preparation remains unsent without an address',async()=>{const r=await post({action:'email.prepare',requestId:'worker-mail-1',callId:call,department:'cse',summary:'Project guidance request',replyTo:'',consent:true,confirmed:true});assert.equal(r.status,200);const d=await r.json();assert.equal(d.status,'recipient_needed')});
 await check('Realtime rejects unverified caller playback before provider access',async()=>{const r=await mf.dispatchFetch('http://desk.test/api/voice',{method:'POST',headers,body:'v=0'});assert.equal(r.status,409);assert.match((await r.json()).error,/Verified voice/)});
 await check('Critical hearing requires confirmation before answering or speech',async()=>{transcription='Is the fee 140000 rupees?';const before=speechCalls;const f=new FormData();f.set('callId',call);f.set('language','en');f.set('audio',new Blob(['synthetic '.repeat(40)],{type:'audio/webm'}),'turn.webm');const d=await (await audioPost(f)).json();assert.equal(d.confirmationRequired,true);assert.equal(d.result,undefined);assert.equal(speechCalls,before)});
 await check('Confirmed text is resolved server-side and exact text reaches TTS',async()=>{failSpeech=false;const f=new FormData();f.set('callId',call);f.set('language','en');f.set('confirmedTranscript','What is the B.Tech tuition fee?');const d=await (await audioPost(f)).json();assert.equal(d.result.decision,'answer');assert.equal(speechInput.text,d.result.reply)});
 async function livePost(path,body,extra={}){
  if(path==='listen'){const f=new FormData();f.set('callId',body.callId);f.set('audio',new Blob([new Uint8Array(512)],{type:'audio/wav'}),'question.wav');const r=new Request('http://desk.test/api/listen',{method:'POST',body:f});return mf.dispatchFetch(r.url,{method:'POST',headers:{...headers,...extra,'Content-Type':r.headers.get('content-type')},body:await r.arrayBuffer()});}
  return mf.dispatchFetch('http://desk.test/api/'+path,{method:'POST',headers:{...headers,'Content-Type':'application/json',...extra},body:JSON.stringify(body)});
 }
 await check('Sarvam listening returns text without exposing a provider credential',async()=>{const r=await livePost('listen',{callId:call,language:'te'});assert.equal(r.status,200);assert.equal(r.headers.get('Cache-Control'),'no-store');const d=await r.json();assert.equal(d.text,transcription);assert.equal(d.value,undefined);assert.equal(sessionInput.get('mode'),'codemix');});
 await check('Streaming speech sends exact authoritative text and PCM after result metadata',async()=>{const r=await livePost('speech',{callId:call,language:'en',kind:'question',text:'What is the B.Tech tuition fee?'});assert.equal(r.status,200);const events=(await r.text()).trim().split('\n').map(x=>JSON.parse(x));assert.equal(events[0].type,'answer');assert.ok(events[0].reply.includes('₹1,40,000'));assert.equal(speechInput.text,events[0].reply);assert.equal(speechInput.output_audio_codec,'linear16');assert.equal(events[1].type,'audio');assert.deepEqual([...Uint8Array.from(atob(events[1].pcm),c=>c.charCodeAt(0))],[0,0,0,128,255,127]);assert.equal(events.at(-1).type,'done')});
 await check('Opening is spoken as a fixed AI disclosure and ignores arbitrary supplied content',async()=>{const r=await livePost('speech',{callId:call,language:'en',kind:'hello',text:'All admissions are guaranteed'});const events=(await r.text()).trim().split('\n').map(x=>JSON.parse(x));assert.match(events[0].reply,/AI assistant/);assert.ok(!events[0].reply.includes('guaranteed'));assert.equal(events[0].result,null)});
 await check('Streaming TTS failure preserves authoritative text but never reports successful speech',async()=>{failSpeech=true;const r=await livePost('speech',{callId:call,language:'en',kind:'question',text:'Who is the CSE HOD?'});const events=(await r.text()).trim().split('\n').map(x=>JSON.parse(x));assert.equal(events[0].type,'answer');assert.equal(events.at(-1).type,'error');assert.ok(!events.some(e=>e.type==='done'));failSpeech=false;});
 await check('Live speech cross-origin and unknown modes are rejected',async()=>{assert.equal((await livePost('speech',{callId:call,language:'en',kind:'question',text:'CSE HOD'},{Origin:'https://evil.test'})).status,403);assert.equal((await livePost('speech',{callId:call,language:'en',kind:'read-anything',text:'invent facts'})).status,400)});
 await check('Crawl evidence is staff-only, paginated and remains unapproved',async()=>{assert.equal((await mf.dispatchFetch('http://desk.test/api/website')).status,401);const r=await mf.dispatchFetch('http://desk.test/api/website',{headers});assert.equal(r.status,200);const d=await r.json();assert.ok(d.documents.length<=25);assert.equal(d.approval,'unreviewed');assert.ok(d.documents.every(x=>x.approval==='unreviewed'&&!x.textPath));});
 await check('Concurrent transcription requests respect the durable per-call cap',async()=>{const quotaCall=(await (await post({action:'call.start',language:'en',channel:'voice'})).json()).id;await db.prepare('INSERT INTO voice_budgets (id,uses,expires_at) VALUES (?,76,?)').bind('call:'+quotaCall+':transcribe',new Date(Date.now()+86400000).toISOString()).run();const responses=await Promise.all(Array.from({length:8},()=>livePost('listen',{callId:quotaCall,language:'en'},{'oai-authenticated-user-id':'quota-owner'})));assert.equal(responses.filter(r=>r.status===200).length,4);assert.equal(responses.filter(r=>r.status===429).length,4);assert.ok(responses.filter(r=>r.status===429).every(r=>r.headers.get('Retry-After')==='60'));});
 await check('Expired voice calls reject speech and listening before provider work',async()=>{const expired=(await (await post({action:'call.start',language:'en',channel:'voice'})).json()).id;await db.prepare('UPDATE calls SET started_at=? WHERE id=?').bind(new Date(Date.now()-20*60000).toISOString(),expired).run();const before=speechCalls;assert.equal((await livePost('listen',{callId:expired,language:'en'})).status,409);assert.equal((await livePost('speech',{callId:expired,language:'en',kind:'hello'})).status,409);assert.equal(speechCalls,before);});
 await check('Ended voice session cannot answer a confirmed transcript',async()=>{await post({action:'call.end',callId:call});const f=new FormData();f.set('callId',call);f.set('language','en');f.set('confirmedTranscript','B.Tech fee');assert.equal((await audioPost(f)).status,409)});
 await check('Ended calls cannot mint listening credentials or stream speech',async()=>{assert.equal((await livePost('listen',{callId:call,language:'en'})).status,409);assert.equal((await livePost('speech',{callId:call,language:'en',kind:'hello'})).status,409)});
 const report={passed:n,total:n,scope:'Compiled Worker HTTP tests with local D1/R2 and synthetic speech-provider replies; no live vendor calls',results};fs.writeFileSync('tests/worker-result.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({passed:n,total:n,scope:report.scope}));
}finally{await mf.dispose()}
