'use client';
import {useRef,useState,useEffect} from 'react';
import {Mic,Square,PhoneOff,VolumeX} from 'lucide-react';
import {api} from '@/lib/client';
import {EndOfTurn,VoiceTurn} from '@/lib/voice-turn';
import type {Language} from '@/lib/policy';
type Line={role:string;text:string;result?:any};
export default function VerifiedVoice({premium,language,onChange}:{premium:boolean;language:Language;onChange:()=>Promise<void>}){
 const [mode,setMode]=useState(premium?'premium':'browser'),[state,setState]=useState('idle'),[lines,setLines]=useState<Line[]>([]),[active,setActive]=useState(false),[error,setError]=useState(''),[auto,setAuto]=useState(true),[latency,setLatency]=useState<number|null>(null),[confirmation,setConfirmation]=useState('');
 const call=useRef<string|null>(null),recognition=useRef<any>(null),recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),audio=useRef<HTMLAudioElement|null>(null),audioUrl=useRef(''),timer=useRef<ReturnType<typeof setTimeout>|null>(null),turn=useRef(new VoiceTurn()),context=useRef<AudioContext|null>(null),frame=useRef(0),endedAt=useRef(0),resume=useRef<()=>void>(()=>{}),alive=useRef(true),autoRef=useRef(auto);
 autoRef.current=auto;
 function clearMic(){if(timer.current)clearTimeout(timer.current);timer.current=null;cancelAnimationFrame(frame.current);if(context.current)void context.current.close().catch(()=>{});context.current=null;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;}
 function halt(){if(recognition.current){recognition.current.onend=null;recognition.current.abort();recognition.current=null;}if(recorder.current){recorder.current.onstop=null;if(recorder.current.state!=='inactive')recorder.current.stop();recorder.current=null;}clearMic();if(audio.current){audio.current.onended=null;audio.current.pause();audio.current.src='';audio.current=null;}if(audioUrl.current)URL.revokeObjectURL(audioUrl.current);audioUrl.current='';window.speechSynthesis?.cancel();}
 function cancel(){turn.current.cancel();halt();setConfirmation('');setState('idle');}
 async function end(){cancel();setActive(false);const id=call.current;call.current=null;if(id){try{await api({action:'call.end',callId:id});await onChange()}catch{if(alive.current)setError('The local session stopped. Call history could not be updated.');}}}
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;turn.current.cancel();halt();if(call.current)void fetch('/api/desk',{method:'POST',keepalive:true,headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'call.end',callId:call.current})});};},[]);
 useEffect(()=>{if(call.current)void end();else cancel();},[language]);
 function failed(id:number,message:string){if(!turn.current.current(id)||!alive.current)return;turn.current.cancel();halt();setState('idle');setError(message);}
 function done(id:number){if(!turn.current.current(id)||!alive.current)return;halt();setState('idle');if(autoRef.current&&call.current)timer.current=setTimeout(()=>{if(autoRef.current&&call.current&&turn.current.current(id))resume.current()},250);}
 function audioStarted(id:number){if(turn.current.current(id)){setState('speaking');setLatency(Math.round(performance.now()-endedAt.current));}}
 async function ensureCall(id:number){if(call.current)return call.current;const c=await api({action:'call.start',channel:'voice',language});if(!turn.current.current(id)||!alive.current){await api({action:'call.end',callId:c.id});return null;}call.current=c.id;setActive(true);setLines([{role:'assistant',text:language==='te'?'హలో, నేను కాలేజీ AI అసిస్టెంట్. ఎలా సహాయం చేయాలి?':language==='hi'?'नमस्ते, मैं कॉलेज की AI सहायक हूँ। कैसे मदद करूँ?':'Hello, I’m the college’s AI assistant. How can I help?'}]);return c.id;}
 async function present(text:string,result:any,id:number,mp3?:string|null){if(!turn.current.current(id)||!call.current)return;setLines(l=>[...l,{role:'caller',text},{role:'assistant',text:result.reply,result}]);void onChange().catch(()=>{});
  if(mp3){audioUrl.current=URL.createObjectURL(new Blob([Uint8Array.from(atob(mp3),c=>c.charCodeAt(0))],{type:'audio/wav'}));const a=new Audio(audioUrl.current);audio.current=a;a.onplaying=()=>audioStarted(id);a.onended=()=>done(id);a.onerror=()=>failed(id,'Speech playback failed. Your verified text answer is shown.');timer.current=setTimeout(()=>failed(id,'Speech playback timed out. Your verified text answer is shown.'),45000);try{await a.play()}catch{failed(id,'Audio playback was blocked. Your verified text answer is shown.');}}
  else if(mode==='browser'){
   if(!window.speechSynthesis){failed(id,'This browser cannot play speech. Your verified answer is shown.');return;}
   const voice=window.speechSynthesis.getVoices().find(v=>v.lang.toLowerCase().startsWith(result.language??language));if((result.language??language)!=='en'&&!voice){failed(id,'No installed voice matches this answer’s language. The verified text is shown.');return;}
   const u=new SpeechSynthesisUtterance(result.reply);u.lang=({en:'en-IN',te:'te-IN',hi:'hi-IN'} as Record<string,string>)[result.language??language];if(voice)u.voice=voice;u.onstart=()=>audioStarted(id);u.onend=()=>done(id);u.onerror=()=>failed(id,'Browser speech failed. Your verified text answer is shown.');timer.current=setTimeout(()=>failed(id,'Browser speech timed out. Your verified text answer is shown.'),45000);window.speechSynthesis.speak(u);
  }else failed(id,'Speech is unavailable. Your verified text answer is shown.');
 }
 async function submit(form:FormData,id:number,signal:AbortSignal){try{const res=await fetch('/api/audio',{method:'POST',body:form,signal:AbortSignal.any([signal,AbortSignal.timeout(55000)])});const data:any=await res.json();if(!turn.current.current(id))return;if(!res.ok)throw new Error(data.error);if(data.confirmationRequired){setConfirmation(data.transcript);setState('confirming');return;}if(data.audioError)setError(data.audioError);await present(data.transcript,data.result,id,data.audio);}catch{failed(id,'I couldn’t complete that voice turn. Please try again or use text.');}}
 async function confirm(){const job=turn.current.begin();halt();setState('thinking');const text=confirmation;setConfirmation('');if(mode==='premium'){const form=new FormData();form.set('callId',call.current!);form.set('language',language);form.set('confirmedTranscript',text);await submit(form,job.id,job.signal);}else{try{const result=await api({action:'call.say',callId:call.current,question:text,language},job.signal);await present(text,result,job.id);}catch{failed(job.id,'I couldn’t check that question. Please try again.');}}}
 async function start(){const job=turn.current.begin();halt();setError('');setConfirmation('');setLatency(null);setState('starting');
  try{if(!await ensureCall(job.id)||!turn.current.current(job.id))return;
   if(mode==='browser'){
    const Recognition=(window as any).SpeechRecognition??(window as any).webkitSpeechRecognition;if(!Recognition)throw new Error('Speech recognition is unavailable. Use a supported browser or premium audio.');
    const r=new Recognition();recognition.current=r;r.lang={en:'en-IN',te:'te-IN',hi:'hi-IN'}[language];r.continuous=false;r.interimResults=false;
    r.onresult=async(e:any)=>{if(!turn.current.current(job.id))return;recognition.current=null;if(timer.current)clearTimeout(timer.current);endedAt.current=performance.now();const heard=e.results[0][0];if((heard.confidence>0&&heard.confidence<0.8)||/\d|₹|name is|my name|పేరు|नाम|tomorrow|రేపు|कल/iu.test(heard.transcript)){setConfirmation(heard.transcript);setState('confirming');return;}setState('thinking');try{const result=await api({action:'call.say',callId:call.current,question:heard.transcript,language},job.signal);await present(heard.transcript,result,job.id);}catch{failed(job.id,'I couldn’t check the college source. Please try again.');}};
    r.onerror=()=>failed(job.id,'No clear speech was received. Check microphone permission and try again.');r.onend=()=>{if(recognition.current===r){recognition.current=null;failed(job.id,'No clear question was received. Please try again.');}};r.start();setState('listening');timer.current=setTimeout(()=>{r.stop();timer.current=setTimeout(()=>failed(job.id,'Speech recognition did not finish. Please try again.'),2000)},30000);
   }else{
    if(!premium)throw new Error('Configure the voice API key and enable live voice first.');if(typeof MediaRecorder==='undefined')throw new Error('This browser cannot record audio.');
    // getUserMedia itself cannot be aborted: late permission results are explicitly disposed.
    timer.current=setTimeout(()=>{if(turn.current.current(job.id)){cancel();setError('Microphone permission timed out. Try again.');}},15000);
    const mic=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true}});if(!turn.current.current(job.id)){mic.getTracks().forEach(t=>t.stop());return;}if(timer.current)clearTimeout(timer.current);stream.current=mic;
    const type=['audio/webm;codecs=opus','audio/mp4','audio/webm'].find(t=>MediaRecorder.isTypeSupported(t));const rec=new MediaRecorder(mic,type?{mimeType:type}:undefined),chunks:Blob[]=[];recorder.current=rec;let lastSpeech=0;
    rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onerror=()=>failed(job.id,'Microphone recording failed. Please try again.');
    rec.onstop=()=>{endedAt.current=lastSpeech||performance.now();clearMic();recorder.current=null;if(!turn.current.current(job.id))return;setState('thinking');const form=new FormData();form.set('callId',call.current!);form.set('language',language);form.set('audio',new Blob(chunks,{type:rec.mimeType}),rec.mimeType.includes('mp4')?'turn.mp4':'turn.webm');void submit(form,job.id,job.signal);};
    rec.start();setState('listening');timer.current=setTimeout(()=>{if(rec.state==='recording')rec.stop()},30000);
    if(autoRef.current){try{const ctx=new AudioContext();context.current=ctx;await ctx.resume();if(!turn.current.current(job.id))return;const analyser=ctx.createAnalyser();analyser.fftSize=2048;ctx.createMediaStreamSource(mic).connect(analyser);const samples=new Float32Array(analyser.fftSize),detector=new EndOfTurn(performance.now());const tick=()=>{if(!turn.current.current(job.id)||rec.state!=='recording')return;analyser.getFloatTimeDomainData(samples);const rms=Math.sqrt(samples.reduce((s,v)=>s+v*v,0)/samples.length),decision=detector.sample(rms,performance.now());lastSpeech=detector.lastSpeech??0;if(decision==='finish'){rec.stop();return;}if(decision==='empty'){failed(job.id,'I didn’t hear a question. Please try again.');return;}frame.current=requestAnimationFrame(tick);};tick();}catch{if(turn.current.current(job.id))setError('Automatic silence detection is unavailable. Use Finish question.');}}
   }
  }catch(e){failed(job.id,(e as Error).message);}
 }
 resume.current=()=>void start();
 return <div className="verified-voice"><div className="voice-mode"><button className={`button ${mode==='premium'?'':'secondary'}`} disabled={active||state!=='idle'} onClick={()=>setMode('premium')}>Premium audio</button><button className={`button ${mode==='browser'?'':'secondary'}`} disabled={active||state!=='idle'} onClick={()=>setMode('browser')}>Browser preview</button></div><h3>{({idle:'A brief answer. In your language.',starting:'Opening microphone…',listening:'Listening — pause when you finish',thinking:'Checking the college source…',speaking:'Speaking — you can interrupt',confirming:'Did I hear this correctly?'} as Record<string,string>)[state]}</h3><p>{mode==='premium'?'The voice reads the server’s verified answer.':'Browser preview: recognition and speech depend on your browser.'}</p><label><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/>Hands-free turns: finish after a pause and listen again after playback</label><div className="voice-mode">{state==='listening'?<button className="button" onClick={()=>{if(recorder.current?.state==='recording')recorder.current.stop();else recognition.current?.stop();}}><Square size={17}/>Finish question</button>:<button className="button" disabled={state==='starting'||(mode==='premium'&&!premium)} onClick={()=>void start()}><Mic size={17}/>{['speaking','thinking'].includes(state)?'Interrupt & speak':'Speak a question'}</button>}{state!=='idle'&&<button className="button secondary" onClick={cancel}><VolumeX size={17}/>Stop</button>}{active&&<button className="button secondary" onClick={()=>void end()}><PhoneOff size={17}/>End conversation</button>}</div>{state==='confirming'&&<div><label>Confirm or correct what I heard<input value={confirmation} maxLength={2000} onChange={e=>setConfirmation(e.target.value)}/></label><button className="button" disabled={!confirmation.trim()} onClick={()=>void confirm()}>Yes, check this question</button></div>}{error&&<p role="alert" className="notice">{error}</p>}{latency!==null&&<p>{latency} ms estimated end of speech → answer playback started ({mode==='premium'?'premium chain':'browser preview'}; device buffering is not measured).</p>}<small>AI voice · microphone audio goes to the selected speech provider · audio is not saved by Campus Desk · use Interrupt & speak during playback</small><div className="voice-lines">{lines.map((l,i)=><div key={i} className={`chat ${l.role}`}><span>{l.role==='caller'?'YOU':'CAMPUS DESK'}</span><p>{l.text}</p>{l.result?.sources?.map((s:any)=><small key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a></small>)}{l.result&&<small>{l.result.latencyMs} ms answer lookup · {l.result.sourceIds?.length?`${l.result.sourceIds.length} approved source(s)`:'Conversation or staff guidance'}</small>}</div>)}</div></div>;
}
