'use client';
import {useRef,useState,useEffect} from 'react';
import {Mic,PhoneOff,Headphones} from 'lucide-react';
import {api} from '@/lib/client';
import {toast} from 'sonner';
export default function VoiceTest({enabled,onChange}:{enabled:boolean;onChange:()=>Promise<void>}){
 const pc=useRef<RTCPeerConnection|null>(null),stream=useRef<MediaStream|null>(null),audio=useRef<HTMLAudioElement|null>(null),call=useRef<string|null>(null),channel=useRef<RTCDataChannel|null>(null);const [status,setStatus]=useState('idle'),[lines,setLines]=useState<string[]>([]);
 function clean(){stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;channel.current?.close();channel.current=null;pc.current?.close();pc.current=null;if(audio.current){audio.current.pause();audio.current.srcObject=null}setStatus('idle');}
 async function stop(){clean();if(call.current){try{await api({action:'call.end',callId:call.current});await onChange()}catch{}call.current=null}}
 useEffect(()=>()=>{stream.current?.getTracks().forEach(t=>t.stop());channel.current?.close();pc.current?.close();if(call.current)void fetch('/api/desk',{method:'POST',keepalive:true,headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'call.end',callId:call.current})});},[]);
 async function start(){setStatus('connecting');setLines([]);try{stream.current=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true}});const p=new RTCPeerConnection();pc.current=p;audio.current=new Audio();audio.current.autoplay=true;p.ontrack=e=>{audio.current!.srcObject=e.streams[0];void audio.current!.play().catch(()=>{})};stream.current.getTracks().forEach(t=>p.addTrack(t,stream.current!));const dc=p.createDataChannel('oai-events');channel.current=dc;const completed=new Set<string>();
 dc.onopen=()=>{setStatus('connected');dc.send(JSON.stringify({type:'response.create',response:{instructions:'Give only your short AI assistant introduction, then ask how you can help.'}}))};
 dc.onmessage=async e=>{try{const event=JSON.parse(e.data);if(event.type==='response.output_audio_transcript.done'||event.type==='response.audio_transcript.done'){setLines(x=>[...x,event.transcript]);if(call.current)await api({action:'call.transcript',callId:call.current,text:event.transcript,role:'spoken_assistant'})}if(event.type==='response.function_call_arguments.done'&&call.current&&!completed.has(event.call_id)){completed.add(event.call_id);let result;const args=JSON.parse(event.arguments);if(event.name==='resolve_query')result=await api({action:'call.say',callId:call.current,question:args.question,language:args.language});else if(event.name==='request_handoff')result=await api({action:'handoff',callId:call.current,...args});else if(event.name==='record_feedback')result=await api({action:'call.feedback',callId:call.current,...args});else if(['start_verification','check_verification','check_student_record','send_information','prepare_department_email'].includes(event.name)){const mapped:Record<string,string>={start_verification:'identity.start',check_verification:'identity.check',check_student_record:'student.lookup',send_information:'message.send',prepare_department_email:'email.prepare'};result=await api({...args,action:mapped[event.name],callId:call.current})}else result={error:'Unsupported tool'};dc.send(JSON.stringify({type:'conversation.item.create',item:{type:'function_call_output',call_id:event.call_id,output:JSON.stringify(result)}}));dc.send(JSON.stringify({type:'response.create'}));await onChange();}if(event.type==='error')toast.error('Voice provider reported a session error. End this test and try again.')}catch{dc.send(JSON.stringify({type:'response.create',response:{instructions:'Say briefly that the office needs to help because the verification tool is unavailable. Do not answer the college question.'}}))}};
 p.onconnectionstatechange=()=>{if(['failed','disconnected'].includes(p.connectionState)){toast.error('Voice connection was interrupted');void stop()}};
 const offer=await p.createOffer();await p.setLocalDescription(offer);const r=await fetch('/api/voice',{method:'POST',headers:{'Content-Type':'application/sdp'},body:offer.sdp});if(!r.ok){const d:any=await r.json();throw new Error(d.error)}call.current=r.headers.get('X-Desk-Call-Id');await p.setRemoteDescription({type:'answer',sdp:await r.text()});await onChange();}catch(e){toast.error((e as Error).message);await stop()}}
 return <div className="voice-test"><div className="mic-orb"><Headphones size={42}/></div><h3>{status==='connected'?'Speak naturally. Interrupt anytime.':status==='connecting'?'Connecting your voice…':'Hear the real conversation'}</h3><p>{enabled?'Uses the live voice provider and the same verified college answer tools. This test is not recorded.':'The microphone test becomes available after the voice API secret is configured and live voice is enabled.'}</p><button className="button" disabled={!enabled||status==='connecting'} onClick={()=>status==='connected'?void stop():void start()}>{status==='connected'?<PhoneOff size={19}/>:<Mic size={19}/>} {status==='connected'?'End voice test':'Start voice test'}</button>{lines.length>0&&<div className="voice-lines">{lines.map((l,i)=><p key={i}>{l}</p>)}</div>}<small>AI assistant · microphone permission requested when you start</small></div>
}
