import type {Fact} from './policy';
// Curated public facts, checked against the official pages on 2026-10-05.
// Recheck dates are review limits, never assertions about the college's academic year.
const observed='2026-10-05';
const root='https://vardhaman.org/';
export const websiteSources=[
 ['College and student portals',root,'verified'],['Programmes, intake and published fees',root+'programmes/','verified'],
 ['Admissions contact',root+'admissions-contact/','verified'],['Category B 2026–27',root+'category-b-admissions-2026-27/','links only; deadline not verified'],
 ['Hostels',root+'hostels/','verified; prices and vacancies not published'],['Transport',root+'transport/','partial; live timings not verified'],
 ['Library',root+'library/','verified'],['Health Centre',root+'health-centre/','verified'],
 ['Academics','https://academics.vardhaman.org/','verified'],['Academic calendars','https://academics.vardhaman.org/academic-calendars/','index verified; linked calendars not imported'],
 ['Examinations','https://examination.vardhaman.org/','verified; current deadlines not verified'],
 ['Computer Science','https://cse.vardhaman.org/','verified; email protected'],['Information Technology','https://it.vardhaman.org/','verified; email protected'],
 ['MBA','https://mba.vardhaman.org/','verified; email protected'],['Career Development','https://pat.vardhaman.org/about-cdc/','verified'],
 ...['cse-aiml','cse-ds','ece','eee','mechanical','civil'].map(d=>[d,`https://${d}.vardhaman.org/`,'not fully retrievable; HOD identity/address needs verification'])
].map(([title,url,status])=>({title,url,status,observedAt:observed}));
const rows:Fact[]=[];
function add(key:string,department:string,title:string,question:string,answer:string,answerTe:string,answerHi:string,source=root,mutable=false){rows.push({id:'vce-'+key,topic:'vce-'+key,department,title,question,answer,answerTe,answerHi,source,status:'approved',access:'public',effectiveFrom:observed,expiresOn:mutable?'2026-11-04':'2027-01-03',approvedBy:'curated:official-website',approvedAt:observed+'T00:00:00Z'});}
add('address','general','Campus address','Where is the college location address campus Kacharam Shamshabad?', 'Vardhaman is in Kacharam, Shamshabad, Ranga Reddy district, Hyderabad, Telangana. The PIN code is 501218.','వర్ధమాన్ కాలేజీ కాచారం, శంషాబాద్, రంగారెడ్డి జిల్లా, హైదరాబాద్‌లో ఉంది. పిన్ కోడ్ 501218.','वर्धमान कॉलेज काचारम, शमशाबाद, रंगा रेड्डी ज़िला, हैदराबाद में है। पिन कोड 501218 है.');
add('phone','general','Main college phone','What is the main college phone contact number?', 'The website lists the main college number as +91 8688901557.','వెబ్‌సైట్‌లో కాలేజీ ప్రధాన నంబర్ +91 8688901557 అని ఉంది.','वेबसाइट पर कॉलेज का मुख्य नंबर +91 8688901557 है।',root,true);
add('code','admissions','Counselling code','What is counselling code EAPCET ECET ICET VMEG?', 'Vardhaman’s EAPCET, ECET and ICET counselling code is VMEG.','వర్ధమాన్ EAPCET, ECET, ICET కౌన్సెలింగ్ కోడ్ VMEG.','वर्धमान का EAPCET, ECET और ICET काउंसलिंग कोड VMEG है।');
add('programmes','admissions','Programmes offered','What courses programmes branches BTech MTech MBA are offered?', 'Vardhaman offers B.Tech, M.Tech and MBA programmes. Which programme are you interested in?','వర్ధమాన్‌లో B.Tech, M.Tech, MBA కోర్సులు ఉన్నాయి. ఏ కోర్సు గురించి తెలుసుకోవాలి?','वर्धमान में B.Tech, M.Tech और MBA हैं। किस पाठ्यक्रम के बारे में जानना चाहेंगे?',root+'programmes/');
add('branches','admissions','B.Tech branches','What BTech engineering branches courses are available?', 'B.Tech branches are CSE, AI and ML, Data Science, IT, ECE, EEE, Mechanical and Civil. Which branch interests you?','B.Tech‌లో CSE, AI & ML, Data Science, IT, ECE, EEE, Mechanical, Civil ఉన్నాయి. ఏ బ్రాంచ్ కావాలి?','B.Tech में CSE, AI और ML, Data Science, IT, ECE, EEE, Mechanical और Civil हैं। कौन सी शाखा चाहिए?',root+'programmes/');
const programs=[['btech','B.Tech','₹1,40,000'],['mtech','M.Tech','₹57,000'],['mba','MBA','₹50,400']];
for(const [id,name,fee] of programs)add('fee-'+id,'accounts',name+' published annual tuition',`What is ${name} tuition annual fee cost fees entha kitna?`, `The website lists ${name} tuition at ${fee} per year. Please confirm your batch’s applicable fee and additional charges with Admissions.`, `వెబ్‌సైట్ ప్రకారం ${name} ట్యూషన్ ఫీజు సంవత్సరానికి ${fee}. మీ బ్యాచ్ ఫీజు, అదనపు ఛార్జీలను అడ్మిషన్స్‌తో నిర్ధారించండి.`, `वेबसाइट पर ${name} की सालाना ट्यूशन फीस ${fee} है। अपने बैच की लागू फीस और अतिरिक्त शुल्क प्रवेश कार्यालय से पुष्टि करें।`,root+'programmes/',true);
const branches=[['cse','CSE',540,'Computer Science computer science engineering'],['cseaiml','CSE AI and ML',180,'Artificial Intelligence Machine Learning AI ML AIML'],['cseds','CSE Data Science',180,'Data Science DS'],['it','Information Technology',180,'Information Technology IT'],['ece','ECE',180,'Electronics Communication ECE'],['eee','EEE',60,'Electrical Electronics EEE'],['mechanical','Mechanical Engineering',30,'Mechanical ME mech'],['civil','Civil Engineering',30,'Civil CE']];
for(const [id,name,count,aliases] of branches)add('intake-'+id,'admissions',name+' listed intake',`What is ${name} ${aliases} seats intake strength?`, `The programme page lists ${count} B.Tech seats in ${name}. This is approved intake, not a count of available admission seats.`, `ప్రోగ్రామ్స్ పేజీలో ${name} B.Tech ఇంటేక్ ${count} సీట్లు. ఇవి ప్రస్తుతం ఖాళీగా ఉన్న సీట్లు అని కాదు.`, `पाठ्यक्रम पृष्ठ पर ${name} में ${count} B.Tech सीटें हैं। यह स्वीकृत क्षमता है, उपलब्ध खाली सीटों की संख्या नहीं।`,root+'programmes/',true);
add('intake-mba','admissions','MBA listed intake','What is MBA seats intake?', 'The website lists an MBA intake of 120. Admissions must confirm current seat availability.','వెబ్‌సైట్‌లో MBA ఇంటేక్ 120 అని ఉంది. ప్రస్తుతం సీట్ల లభ్యతను అడ్మిషన్స్ నిర్ధారించాలి.','वेबसाइट पर MBA की क्षमता 120 है। मौजूदा सीट उपलब्धता प्रवेश कार्यालय से पूछें।',root+'programmes/',true);
add('mtech-courses','admissions','M.Tech specialisations','What MTech courses specialisations branches?', 'M.Tech options include CSE, Power Electronics and Electrical Drives, Digital Electronics and Communication Systems, Structural Engineering, and Engineering Design.','M.Tech‌లో CSE, Power Electronics and Electrical Drives, Digital Electronics and Communication Systems, Structural Engineering, Engineering Design ఉన్నాయి.','M.Tech में CSE, Power Electronics and Electrical Drives, Digital Electronics and Communication Systems, Structural Engineering और Engineering Design हैं।',root+'programmes/');
add('eligibility-btech','admissions','Published B.Tech requirements','What is BTech admission eligibility requirements qualification entrance test?', 'The website lists 10+2 with Maths, Physics and Chemistry, with 45% aggregate or 40% for reserved categories. Admissions must confirm your eligibility.','వెబ్‌సైట్‌లో Maths, Physics, Chemistryతో 10+2, 45% మార్కులు లేదా రిజర్వ్డ్ కేటగిరీలకు 40% అని ఉంది. మీ అర్హతను అడ్మిషన్స్ నిర్ధారించాలి.','वेबसाइट पर Maths, Physics, Chemistry के साथ 10+2 में 45%, आरक्षित श्रेणियों के लिए 40% है। आपकी पात्रता प्रवेश कार्यालय पुष्टि करेगा।',root+'programmes/',true);
add('eligibility-mtech','admissions','Published M.Tech requirements','What is MTech admission eligibility qualification entrance?', 'The website lists a relevant engineering degree with 50% marks, or 45% for reserved categories, and GATE or PGECET admission routes.','వెబ్‌సైట్‌లో సంబంధిత ఇంజినీరింగ్ డిగ్రీలో 50%, రిజర్వ్డ్ కేటగిరీలకు 45%, GATE లేదా PGECET అడ్మిషన్ మార్గాలు ఉన్నాయి.','वेबसाइट पर संबंधित इंजीनियरिंग डिग्री में 50%, आरक्षित श्रेणियों के लिए 45%, और GATE या PGECET प्रवेश मार्ग बताए गए हैं।',root+'programmes/',true);
add('eligibility-mba','admissions','Published MBA requirements','What is MBA admission eligibility qualification entrance ICET?', 'The website lists an undergraduate degree with 50% marks, or 45% for reserved categories, and TGICET for MBA admissions.','వెబ్‌సైట్‌లో డిగ్రీలో 50%, రిజర్వ్డ్ కేటగిరీలకు 45%, MBA అడ్మిషన్లకు TGICET అని ఉంది.','वेबसाइट पर स्नातक में 50%, आरक्षित श्रेणियों के लिए 45%, और MBA प्रवेश के लिए TGICET बताया गया है।',root+'programmes/',true);
add('admissions-contact','admissions','Dean of Admissions contact','Who handles admissions dean Santosh contact phone?', 'The admissions page lists Dr. K Santosh Reddy, Dean of Admissions, at +91 9014350450.','అడ్మిషన్స్ పేజీలో డీన్ Dr. K Santosh Reddy నంబర్ +91 9014350450 అని ఉంది.','प्रवेश पृष्ठ पर Dean of Admissions Dr. K Santosh Reddy का नंबर +91 9014350450 है।',root+'admissions-contact/',true);
add('category-b','admissions','Category B notice index','Where is Category B management quota admission application 2026 2027?', 'The official Category B 2026–27 page has notification, application, merit-list and interview links. I haven’t verified a current deadline.','Category B 2026–27 పేజీలో నోటిఫికేషన్, అప్లికేషన్, మెరిట్ లిస్ట్, ఇంటర్వ్యూ లింకులు ఉన్నాయి. ప్రస్తుత చివరి తేదీ నిర్ధారణ కాలేదు.','Category B 2026–27 पृष्ठ पर सूचना, आवेदन, मेरिट सूची और इंटरव्यू लिंक हैं। वर्तमान अंतिम तारीख सत्यापित नहीं है।',root+'category-b-admissions-2026-27/',true);
add('hostel-facilities','hostel','Published hostel facilities','Is there a hostel accommodation facilities wifi laundry security?', 'The hostel page describes Wi-Fi, dining, laundry, recreation and security facilities. The Hostel Office must confirm room availability and charges.','హాస్టల్ పేజీలో Wi-Fi, భోజనం, లాండ్రీ, వినోదం, భద్రత సౌకర్యాలు ఉన్నాయి. గదులు, ఛార్జీలను హాస్టల్ ఆఫీసుతో నిర్ధారించండి.','हॉस्टल पृष्ठ पर Wi-Fi, भोजन, लॉन्ड्री, मनोरंजन और सुरक्षा सुविधाएँ हैं। कमरे और शुल्क हॉस्टल कार्यालय से पुष्टि करें।',root+'hostels/');
add('transport','transport','Official transport route directory','Is there college bus transport service routes?', 'The website publishes college bus routes and stops. Which pickup area do you need?','వెబ్‌సైట్‌లో కాలేజీ బస్సు రూట్లు, స్టాప్‌లు ఉన్నాయి. మీకు ఏ ప్రాంతం నుంచి బస్సు కావాలి?','वेबसाइट पर कॉलेज बस के मार्ग और स्टॉप हैं। किस इलाके से बस चाहिए?',root+'transport/',true);
add('payment-link','accounts','Official tuition payment portal','Where can I pay tuition fees online payment portal link?', 'Use the tuition payment link on the official college website. It opens fees.vardhaman.org; I can’t check your personal payment status yet.','అధికారిక కాలేజీ వెబ్‌సైట్‌లో ట్యూషన్ పేమెంట్ లింక్ వాడండి. అది fees.vardhaman.org తెరుస్తుంది. మీ వ్యక్తిగత పేమెంట్ స్టేటస్ ఇంకా చూడలేను.','कॉलेज की आधिकारिक वेबसाइट का ट्यूशन भुगतान लिंक इस्तेमाल करें। वह fees.vardhaman.org खोलता है। व्यक्तिगत भुगतान स्थिति अभी नहीं देख सकती।');
add('student-login','general','Official student portal','Where is student login portal students corner?', 'The official website’s Student Login link opens studentscorner.vardhaman.org. Keep your password and OTP private.','అధికారిక వెబ్‌సైట్ Student Login లింక్ studentscorner.vardhaman.org తెరుస్తుంది. మీ పాస్‌వర్డ్, OTP ఎవరికీ చెప్పకండి.','आधिकारिक वेबसाइट का Student Login लिंक studentscorner.vardhaman.org खोलता है। अपना पासवर्ड और OTP निजी रखें।');
add('calendar','academics','Academic calendar index','Where is academic calendar timetable holiday schedule?', 'The academic calendar page lists calendars by programme, year and semester. Which programme and year do you need?','అకడమిక్ క్యాలెండర్ పేజీలో కోర్సు, సంవత్సరం, సెమిస్టర్ ప్రకారం క్యాలెండర్లు ఉన్నాయి. ఏ కోర్సు, సంవత్సరం కావాలి?','अकादमिक कैलेंडर पृष्ठ पर पाठ्यक्रम, वर्ष और सेमेस्टर के अनुसार कैलेंडर हैं। कौन सा पाठ्यक्रम और वर्ष चाहिए?','https://academics.vardhaman.org/academic-calendars/',true);
add('exams-portal','exams','Examination website','Where is examination results hall ticket exam schedules portal?', 'The Examination Branch website has results, rules and student verification links. Which exam or notice are you looking for?','ఎగ్జామినేషన్ వెబ్‌సైట్‌లో రిజల్ట్స్, రూల్స్, స్టూడెంట్ వెరిఫికేషన్ లింకులు ఉన్నాయి. ఏ పరీక్ష లేదా నోటీసు కావాలి?','परीक्षा शाखा की वेबसाइट पर परिणाम, नियम और छात्र सत्यापन लिंक हैं। किस परीक्षा या सूचना की ज़रूरत है?','https://examination.vardhaman.org/');
add('library-location','academics','Library location','Where is central library block location?', 'The central library is in Block 6, across two floors.','సెంట్రల్ లైబ్రరీ బ్లాక్ 6లో రెండు అంతస్తుల్లో ఉంది.','केंद्रीय पुस्तकालय Block 6 में दो मंज़िलों पर है।',root+'library/');
add('library-hours','academics','Library published hours','When is library open hours timing closing?', 'The website lists library hours as 8 a.m. to 8 p.m., closed on holidays. Circulars can change these timings.','వెబ్‌సైట్ ప్రకారం లైబ్రరీ ఉదయం 8 నుంచి రాత్రి 8 వరకు. సెలవుల్లో మూసి ఉంటుంది; సర్క్యులర్ల ప్రకారం సమయాలు మారవచ్చు.','वेबसाइट पर पुस्तकालय का समय सुबह 8 से रात 8 है, छुट्टियों पर बंद। परिपत्रों से समय बदल सकता है।',root+'library/',true);
add('library-borrow','academics','Student library borrowing','How many library books borrow loan return days?', 'The library page lists five books for B.Tech, M.Tech and MBA students, for fourteen days. A valid college ID and membership are required.','లైబ్రరీ పేజీ ప్రకారం B.Tech, M.Tech, MBA విద్యార్థులకు ఐదు పుస్తకాలు, పద్నాలుగు రోజుల గడువు. కాలేజీ ID, మెంబర్‌షిప్ అవసరం.','पुस्तकालय पृष्ठ पर B.Tech, M.Tech और MBA छात्रों के लिए पाँच किताबें, चौदह दिन हैं। वैध कॉलेज ID और सदस्यता चाहिए।',root+'library/',true);
add('library-circulation','academics','Library issues and returns hours','When can library books issue return circulation?', 'The website lists library book issues and returns from 9 a.m. to 6 p.m. Check the latest library circular for changes.','వెబ్‌సైట్‌లో పుస్తకాల ఇష్యూ, రిటర్న్స్ ఉదయం 9 నుంచి సాయంత్రం 6 వరకు అని ఉంది. తాజా లైబ్రరీ సర్క్యులర్ చూడండి.','वेबसाइट पर किताबों का निर्गमन और वापसी सुबह 9 से शाम 6 है। बदलाव के लिए नवीनतम पुस्तकालय परिपत्र देखें।',root+'library/',true);
add('health','general','Campus health centre','Is there a health centre doctor infirmary first aid medical facility?', 'The website describes an on-campus health centre with doctors during working hours and first-aid facilities. Contact campus staff for current assistance.','వెబ్‌సైట్‌లో క్యాంపస్ హెల్త్ సెంటర్, పని వేళల్లో డాక్టర్లు, ప్రథమ చికిత్స సౌకర్యాలు ఉన్నాయి. ప్రస్తుత సహాయానికి క్యాంపస్ సిబ్బందిని సంప్రదించండి.','वेबसाइट पर कैंपस स्वास्थ्य केंद्र, कार्य समय में डॉक्टर और प्राथमिक उपचार की सुविधा है। वर्तमान मदद के लिए कैंपस कर्मचारी से संपर्क करें।',root+'health-centre/');
add('placements','placements','Career Development support','What placement training internships career development CDC support?', 'The Career Development Cell supports placements, internships, competitive-exam preparation and higher-study guidance. It doesn’t guarantee a job for an individual student.','Career Development Cell ప్లేస్‌మెంట్స్, ఇంటర్న్‌షిప్స్, పోటీ పరీక్షలు, ఉన్నత చదువులకు సహాయం చేస్తుంది. వ్యక్తిగత ఉద్యోగ హామీ కాదు.','Career Development Cell प्लेसमेंट, इंटर्नशिप, प्रतियोगी परीक्षा और उच्च शिक्षा मार्गदर्शन देता है। किसी छात्र को नौकरी की गारंटी नहीं है।','https://pat.vardhaman.org/about-cdc/');
for(const [id,name,hod,url] of [['cse','CSE','Dr. Y. Vijayalata','https://cse.vardhaman.org/'],['it','Information Technology','Dr. Sreenivasulu Gogula','https://it.vardhaman.org/'],['mba','MBA','Manish K Srivastava','https://mba.vardhaman.org/']])add('hod-'+id,id,name+' HOD',`Who is ${name} head department HOD?`, `The department page lists ${hod} as the ${name} Head of Department.`, `డిపార్ట్‌మెంట్ పేజీలో ${name} HOD ${hod} అని ఉంది.`, `विभाग के पृष्ठ पर ${name} के HOD ${hod} हैं।`,url,true);
add('mba-specialisations','mba','MBA specialisations','What MBA specialisations finance HR marketing entrepreneurship?', 'The MBA page lists Finance, Human Resources, Marketing and Entrepreneurship specialisations.','MBA పేజీలో Finance, Human Resources, Marketing, Entrepreneurship స్పెషలైజేషన్లు ఉన్నాయి.','MBA पृष्ठ पर Finance, Human Resources, Marketing और Entrepreneurship विशेषज्ञताएँ हैं।','https://mba.vardhaman.org/');
export const collegeFacts=rows;
export const departmentDirectory=[
 {id:'admissions',name:'Dr. K Santosh Reddy',source:root+'admissions-contact/'},
 {id:'cse',name:'Dr. Y. Vijayalata',source:'https://cse.vardhaman.org/'},
 {id:'it',name:'Dr. Sreenivasulu Gogula',source:'https://it.vardhaman.org/'},
 {id:'mba',name:'Manish K Srivastava',source:'https://mba.vardhaman.org/'}
];
