import { z } from 'zod';
import { database,uid,now,log,redact,runtime } from './store';
import { decide,detectLanguage,departmentNames,crisp,validFact,type Fact,type Language } from './policy';
import {collegeFacts,callReviewFacts,websiteSources,departmentDirectory} from './college-data';
import {contextualQuestion} from './college-intent';
import {prepareEmail,sendDepartmentEmail,recipientCurrent} from './department-email';
import {smtpConfigured} from './smtp';
import { runEvaluation } from './evaluation';
import { semanticResolve } from './semantic';
import { identityStart,identityCheck,studentLookup,sendFollowup } from './integrations';
const deps=Object.keys(departmentNames) as [string,...string[]];
const id=z.string().min(1).max(160),str=z.string().trim().min(1).max(500),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(x=>!Number.isNaN(Date.parse(x))&&new Date(x).toISOString().startsWith(x),'Invalid date');
export const factSchema=z.object({id:id.optional(),title:str,department:z.enum(deps),topic:z.string().min(1).max(100),question:z.string().min(3).max(2000),answer:str.refine(crisp,'Use at most 55 words and no lists'),answerTe:z.string().max(500).default(''),answerHi:z.string().max(500).default(''),source:str,effectiveFrom:date,expiresOn:date,access:z.enum(['public','private']).default('public')}).refine(x=>x.effectiveFrom<=x.expiresOn,'Expiry must be after the effective date').refine(x=>!x.answerTe||crisp(x.answerTe),'Telugu answer must be concise').refine(x=>!x.answerHi||crisp(x.answerHi),'Hindi answer must be concise');
export async function seed(){const db=database();await db.batch([
 db.prepare('INSERT OR IGNORE INTO settings (id,value) VALUES (?,?)').bind('config',JSON.stringify({collegeName:'Vardhaman College of Engineering',retentionDays:30,recordingEnabled:false,voiceEnabled:false,replyWords:30,timeZone:'Asia/Kolkata'})),
 ...deps.map(d=>db.prepare('INSERT OR IGNORE INTO departments (id,name,target,hours,days,enabled) VALUES (?,?,?,?,?,0)').bind(d,departmentNames[d],'','09:00–17:00','1,2,3,4,5'))]);
 const marker=await db.prepare("SELECT id FROM settings WHERE id='website-v2-loaded'").first();
 if(!marker)await db.batch([
 ...collegeFacts.map(f=>db.prepare('INSERT OR IGNORE INTO knowledge (id,title,department,topic,question,answer,answer_te,answer_hi,source,status,access,effective_from,expires_on,approved_by,approved_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(f.id,f.title,f.department,f.topic,f.question,f.answer,f.answerTe,f.answerHi,f.source,f.status,f.access,f.effectiveFrom,f.expiresOn,f.approvedBy,f.approvedAt,now())),
 ...deps.map(d=>{const info=departmentDirectory.find(x=>x.id===d);return db.prepare("INSERT OR IGNORE INTO email_directory (id,recipient_name,email,source,updated_at) VALUES (?, ?, '', ?, ?)").bind(d,info?.name??'',info?.source??'',now())}),
 db.prepare("INSERT OR IGNORE INTO settings (id,value) VALUES ('website-v2-loaded',?)").bind(now())]);
 const reviewed=await db.prepare("SELECT id FROM settings WHERE id='call-review-2026-10-08'").first();
 if(!reviewed)await db.batch([
 ...callReviewFacts.map(f=>db.prepare('INSERT OR IGNORE INTO knowledge (id,title,department,topic,question,answer,answer_te,answer_hi,source,status,access,effective_from,expires_on,approved_by,approved_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(f.id,f.title,f.department,f.topic,f.question,f.answer,f.answerTe,f.answerHi,f.source,f.status,f.access,f.effectiveFrom,f.expiresOn,f.approvedBy,f.approvedAt,now())),
 db.prepare("INSERT OR IGNORE INTO settings (id,value) VALUES ('call-review-2026-10-08',?)").bind(now())]);
 }
export async function config(){await seed();const row=await database().prepare('SELECT value FROM settings WHERE id=?').bind('config').first<{value:string}>();return JSON.parse(row!.value);}
export async function facts(){const {results}=await database().prepare('SELECT id,title,department,topic,question,answer,answer_te AS answerTe,answer_hi AS answerHi,source,status,access,effective_from AS effectiveFrom,expires_on AS expiresOn,approved_by AS approvedBy,approved_at AS approvedAt,updated_at AS updatedAt FROM knowledge ORDER BY updated_at DESC').all();return results as unknown as Fact[];}
export async function overview(){await seed();const db=database();const r=await Promise.all([facts(),config(),db.prepare('SELECT * FROM departments').all(),db.prepare('SELECT * FROM calls ORDER BY started_at DESC LIMIT 200').all(),db.prepare('SELECT * FROM tickets ORDER BY created_at DESC LIMIT 200').all(),db.prepare('SELECT * FROM audit ORDER BY created_at DESC LIMIT 40').all(),db.prepare('SELECT * FROM evaluations ORDER BY created_at DESC,rowid DESC LIMIT 10').all(),db.prepare("SELECT decision, COUNT(*) AS count, AVG(latency_ms) AS latency FROM turns WHERE role='assistant' GROUP BY decision").all(),db.prepare('SELECT * FROM email_directory').all(),db.prepare('SELECT * FROM email_outbox ORDER BY created_at DESC LIMIT 200').all()]);return {knowledge:r[0],config:r[1],departments:r[2].results,calls:r[3].results,tickets:r[4].results,audit:r[5].results,evaluations:r[6].results,metrics:r[7].results,emailDirectory:r[8].results,emailOutbox:r[9].results,diagnostics:{reviewQueue:(r[0] as Fact[]).filter(f=>f.status!=='approved'||f.expiresOn<new Date().toISOString().slice(0,10)||f.effectiveFrom>new Date().toISOString().slice(0,10)),missingTopics:(await db.prepare("SELECT question AS summary,COUNT(*) AS count,MAX(created_at) AS last_seen FROM (SELECT t.created_at,(SELECT p.text FROM turns p WHERE p.call_id=t.call_id AND p.role='caller' AND p.rowid<t.rowid ORDER BY p.rowid DESC LIMIT 1) AS question FROM turns t WHERE t.role='assistant' AND t.decision='escalate') GROUP BY question ORDER BY count DESC LIMIT 30").all()).results},websiteSources,connections:{smtp:smtpConfigured()||(!!runtime().SMTP_ADAPTER_URL&&!!runtime().SMTP_ADAPTER_TOKEN),voice:!!runtime().SARVAM_API_KEY,transfer:!!runtime().TRANSFER_ADAPTER_URL,erp:!!runtime().ERP_ADAPTER_URL,recordings:!!runtime().RECORDINGS,service:!!runtime().DESK_SERVICE_TOKEN,messaging:!!runtime().MESSAGE_ADAPTER_URL}};}
export async function loadCall(callId:string){const c=await database().prepare('SELECT * FROM calls WHERE id=?').bind(callId).first();if(!c)throw new Error('Call not found');return c;}
export async function startCall(language:Language,channel='lab',actor='service:voice',callId=uid()){await seed();await database().prepare('INSERT INTO calls (id,channel,language,status,department,started_at,consent,review_status,review_note,summary) VALUES (?,?,?,\'active\',\'general\',?,0,\'unreviewed\',\'\',\'\')').bind(callId,channel,language,now()).run();await log(actor,'call.started',callId,channel);return {id:callId};}
export async function resolveQuery(callId:string,question:string,language:Language,actor:string,signal?:AbortSignal){signal?.throwIfAborted();const t=Date.now(),db=database(),c=await loadCall(callId);if(c.status!=='active')throw new Error('This call has ended. Start another conversation.');
 const prev=await db.prepare("SELECT text,decision,source_ids AS sourceIds FROM turns WHERE call_id=? AND role='assistant' ORDER BY created_at DESC,rowid DESC LIMIT 1").bind(callId).first<{text:string;decision:string;sourceIds:string}>();
 const priorCaller=await db.prepare("SELECT text FROM turns WHERE call_id=? AND role='caller' ORDER BY created_at DESC,rowid DESC LIMIT 1").bind(callId).first<{text:string}>();
 const records=await facts(),previousFact=records.find(f=>f.id===JSON.parse(prev?.sourceIds??'[]')[0]);
 let q=contextualQuestion(question,previousFact?.question??priorCaller?.text??'',prev?.text??''); // Scoped, elliptical follow-ups only.
 if(prev?.decision==='clarify'&&/regular|supplementary|రెగ్యులర్|సప్లిమెంటరీ|नियमित|सप्ली/iu.test(q)){const last=await db.prepare("SELECT text FROM turns WHERE call_id=? AND role='caller' ORDER BY created_at DESC,rowid DESC LIMIT 1").bind(callId).first<{text:string}>();if(last)q=`${last.text} ${q}`;}
 const lang=detectLanguage(question,language),day=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const basic=decide(q,records,lang,day,prev?.decision==='clarify'?prev.text:undefined);
 let result=await semanticResolve(q,records,lang,day,basic,signal);
 // A staff edit/withdrawal can happen while the semantic provider is in flight.
 if(result.sourceIds.length){
  const latest=await facts();
  const selected=latest.filter(f=>result.sourceIds.includes(f.id));
  const changed=selected.length!==result.sourceIds.length||selected.some(f=>!validFact(f,day)||(lang==='te'?f.answerTe:lang==='hi'?f.answerHi:f.answer)!==result.reply||latest.some(other=>other.department===f.department&&other.topic===f.topic&&validFact(other,day)&&other.answer.trim()!==f.answer.trim()));
  if(changed)result={...result,decision:'escalate',sourceIds:[],reason:'Source authority changed while resolving',reply:lang==='te'?'సమాచారం మళ్లీ నిర్ధారించాలి. ఆఫీసు సహాయం కావాలా?':lang==='hi'?'जानकारी दोबारा सत्यापित करनी होगी। क्या कार्यालय से मदद चाहिए?':'That information needs to be checked again. Would you like help from the office?'};
 }

 signal?.throwIfAborted();if((await loadCall(callId)).status!=='active')throw new Error('This call has ended.');
 await db.batch([db.prepare('INSERT INTO turns (id,call_id,role,text,decision,source_ids,latency_ms,created_at) VALUES (?,?,\'caller\',?,NULL,\'[]\',0,?)').bind(uid(),callId,redact(question),now()),db.prepare('INSERT INTO turns (id,call_id,role,text,decision,source_ids,latency_ms,created_at) VALUES (?,?,\'assistant\',?,?,?,?,?)').bind(uid(),callId,result.reply,result.decision,JSON.stringify(result.sourceIds),Date.now()-t,now()),db.prepare('UPDATE calls SET language=?,department=?,summary=? WHERE id=?').bind(lang,result.department,redact(question).slice(0,500),callId)]);await log(actor,'query.resolved',callId,`${result.decision}: ${result.reason}`);return {...result,sources:records.filter(f=>result.sourceIds.includes(f.id)).map(f=>({title:f.title,url:f.source})),latencyMs:Date.now()-t,language:lang};}
export function officeOpen(d:Record<string,unknown>,at=new Date()){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',weekday:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(at);const day=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(parts.find(p=>p.type==='weekday')!.value),hh=Number(parts.find(p=>p.type==='hour')!.value),mm=Number(parts.find(p=>p.type==='minute')!.value),time=hh*60+mm;const m=String(d.hours).match(/^(\d\d):(\d\d)[–-](\d\d):(\d\d)$/);return !!m&&String(d.days).split(',').includes(String(day))&&time>=Number(m[1])*60+Number(m[2])&&time<Number(m[3])*60+Number(m[4]);}
async function ticket(callId:string|null,department:string,summary:string,category:string,contact='',callbackAt:string|null=null){const id=uid(),db=database();await db.prepare('INSERT INTO tickets (id,call_id,department,category,summary,status,created_at,updated_at,callback_at,contact,priority) VALUES (?,?,?,?,?,\'open\',?,?,?,?,\'normal\')').bind(id,callId,department,category,redact(summary),now(),now(),callbackAt,contact).run();return id;}
export async function handoff(callId:string,department:string,summary:string,consent:boolean,actor:string){if(!consent)throw new Error('Caller agreement is required');const c=await loadCall(callId);if(c.status!=='active')throw new Error('This call has ended');const db=database(),d=await db.prepare('SELECT * FROM departments WHERE id=?').bind(department).first();if(!d)throw new Error('Unknown department');const ticketId=await ticket(callId,department,summary,'handoff');const fallback={status:'callback_requested',ticketId,reply:'I’ve logged your request for the office. A callback time has not been confirmed.'};
 if(c.channel==='lab'||!d.enabled||!d.target||!officeOpen(d)||!runtime().TRANSFER_ADAPTER_URL){await log(actor,'handoff.callback_requested',callId,`${department}; ${c.channel==='lab'?'test call':'office or transfer unavailable'}`);return fallback;}
 try{const r=await fetch(runtime().TRANSFER_ADAPTER_URL!,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${runtime().TRANSFER_ADAPTER_TOKEN??''}`},body:JSON.stringify({callId,department,target:d.target,ticketId,summary:redact(summary),mode:'warm'}),signal:AbortSignal.timeout(8000)});if(!r.ok)throw new Error('Transfer provider unavailable');const result=await r.json() as {status?:string};
 const status=result.status==='connected'?'connected':result.status==='initiated'?'initiated':'callback_requested';await log(actor,`handoff.${status}`,callId,department);if(status==='connected')await db.prepare('UPDATE calls SET status=\'transferred\',ended_at=? WHERE id=?').bind(now(),callId).run();return {...fallback,status,reply:status==='connected'?'You’re connected to the office now.':status==='initiated'?'The office connection has been requested. Please hold briefly.':fallback.reply};}catch{await log(actor,'handoff.failed',callId,department);return fallback;}}
export async function action(input:unknown,actor:string,signal?:AbortSignal){const p=z.object({action:z.string()}).passthrough().parse(input) as Record<string,unknown>&{action:string};const db=database();const admin=()=>{if(!actor.startsWith('staff:'))throw new Error('Staff access is required');};
 switch(p.action){
 case 'email.directory.save':{admin();const b=z.object({id:z.enum(deps),name:z.string().trim().max(160),email:z.union([z.string().email(),z.literal('')]),source:z.string().max(500),verified:z.boolean()}).refine(x=>!x.verified||(!!x.email&&!!x.name&&/^https:\/\//.test(x.source)),'Verification needs a recipient name, email and official HTTPS source').parse(p);await db.prepare('UPDATE email_directory SET recipient_name=?,email=?,source=?,verified_by=?,verified_at=?,verified_until=?,updated_at=? WHERE id=?').bind(b.name,b.email,b.source,b.verified?actor:null,b.verified?now():null,b.verified?new Date(Date.now()+30*86400000).toISOString():null,now(),b.id).run();await log(actor,'email.recipient_updated',b.id,b.verified?'staff verified':'unverified');return {ok:true};}
 case 'email.prepare':{const b=z.object({requestId:id,callId:id.nullable().optional(),department:z.enum(deps),summary:str,replyTo:z.union([z.string().email().max(200),z.literal('')]),consent:z.boolean(),confirmed:z.boolean()}).parse(p);await seed();return prepareEmail(b,actor);}
 case 'email.edit':{admin();const b=z.object({id,subject:z.string().trim().min(1).max(160).refine(x=>!/[\r\n]/.test(x)),body:z.string().trim().min(1).max(2000),confirmed:z.literal(true),consent:z.literal(true)}).parse(p);const changed=await db.prepare("UPDATE email_outbox SET subject=?,body=?,reviewed_by=NULL,reviewed_at=NULL,recipient_verified_at=NULL,detail='Edited; caller reconfirmed; staff review required',updated_at=? WHERE id=? AND status IN ('draft','recipient_needed') RETURNING id").bind(b.subject,b.body,now(),b.id).first();if(!changed)throw new Error('Only unsent drafts can be edited');await log(actor,'email.edited',b.id,'Caller reconfirmed and consented; review revoked');return {ok:true};}
 case 'email.review':{admin();const b=z.object({id}).parse(p);const e=await db.prepare('SELECT * FROM email_outbox WHERE id=?').bind(b.id).first();if(!e||!['draft','recipient_needed'].includes(String(e.status)))throw new Error('This email cannot be readdressed after a send attempt');const d=await db.prepare('SELECT * FROM email_directory WHERE id=?').bind(e.department).first();if(!recipientCurrent(d))throw new Error('Verify the department recipient first; verification is missing or expired');const changed=await db.prepare("UPDATE email_outbox SET recipient=?,recipient_name=?,status='draft',reviewed_by=?,reviewed_at=?,recipient_verified_at=?,detail='Recipient and message reviewed by staff',updated_at=? WHERE id=? AND status IN ('draft','recipient_needed') AND body=? AND subject=? RETURNING id").bind(d!.email,d!.recipient_name,actor,now(),d!.verified_at,now(),b.id,e.body,e.subject).first();if(!changed)throw new Error('Draft changed during review; open it again');await log(actor,'email.reviewed',b.id,String(e.department));return {ok:true};}
 case 'email.send':{admin();return sendDepartmentEmail(id.parse(p.id),actor);}
 case 'identity.start':{const b=z.object({callId:id,studentId:z.string().min(3).max(80),consent:z.boolean()}).parse(p);return identityStart(b.callId,b.studentId,b.consent,actor);}
 case 'identity.check':{const b=z.object({callId:id}).parse(p);return identityCheck(b.callId,actor);}
 case 'student.lookup':{const b=z.object({callId:id,resource:z.enum(['fee-status','attendance','application-status','hostel-status'])}).parse(p);return studentLookup(b.callId,b.resource,actor);}
 case 'message.send':{const b=z.object({callId:id,sourceId:id,channel:z.enum(['sms','email']),recipient:z.string().min(3).max(200),consent:z.boolean(),confirmed:z.boolean()}).refine(x=>x.channel==='sms'?/^\+\d{8,15}$/.test(x.recipient):z.string().email().safeParse(x.recipient).success,'Recipient is invalid').parse(p);return sendFollowup(b.callId,b.sourceId,b.channel,b.recipient,b.consent,b.confirmed,actor);}
 case 'call.start':{const b=z.object({language:z.enum(['en','te','hi']).default('en'),channel:z.enum(['lab','voice','phone']).default('lab'),id:id.optional()}).parse(p);return startCall(b.language,b.channel,actor,b.id);}
 case 'call.say':{const b=z.object({callId:id,question:z.string().trim().min(1).max(2000),language:z.enum(['en','te','hi']).default('en')}).parse(p);return resolveQuery(b.callId,b.question,b.language,actor,signal);}
 case 'call.transcript':{const b=z.object({callId:id,text:z.string().max(4000),role:z.enum(['spoken_caller','spoken_assistant'])}).parse(p);await loadCall(b.callId);let decision:string|null=null;if(b.role==='spoken_assistant'){const last=await db.prepare("SELECT text FROM turns WHERE call_id=? AND role='assistant' ORDER BY created_at DESC,rowid DESC LIMIT 1").bind(b.callId).first<{text:string}>();decision=last?.text.trim()===b.text.trim()?'exact_tool_reply':'spoken_output_review';if(last&&decision==='spoken_output_review')await db.prepare("UPDATE calls SET review_status='needs_review',review_note='Spoken output differs from the verified tool reply; review the transcript.' WHERE id=?").bind(b.callId).run();}await db.prepare('INSERT INTO turns (id,call_id,role,text,decision,source_ids,latency_ms,created_at) VALUES (?,?,?,?,?,\'[]\',0,?)').bind(uid(),b.callId,b.role,redact(b.text),decision,now()).run();return {ok:true};}
 case 'call.end':{const b=z.object({callId:id}).parse(p);await loadCall(b.callId);await db.prepare('UPDATE calls SET status=CASE WHEN status=\'active\' THEN \'completed\' ELSE status END,ended_at=? WHERE id=?').bind(now(),b.callId).run();await log(actor,'call.ended',b.callId,'');return {ok:true};}
 case 'call.consent':{const b=z.object({callId:id,consent:z.boolean()}).parse(p);await loadCall(b.callId);await db.prepare('UPDATE calls SET consent=? WHERE id=?').bind(b.consent?1:0,b.callId).run();await log(actor,'recording.consent',b.callId,String(b.consent));return {ok:true};}
 case 'call.feedback':{const b=z.object({callId:id,rating:z.number().int().min(1).max(5)}).parse(p);await loadCall(b.callId);await db.prepare('UPDATE calls SET feedback=? WHERE id=?').bind(b.rating,b.callId).run();return {ok:true};}
 case 'call.review':{admin();const b=z.object({callId:id,status:z.enum(['accurate','needs_review','incorrect']),note:z.string().max(2000)}).parse(p);await loadCall(b.callId);await db.prepare('UPDATE calls SET review_status=?,review_note=? WHERE id=?').bind(b.status,b.note,b.callId).run();await log(actor,'call.reviewed',b.callId,b.status);return {ok:true};}
 case 'handoff':{const b=z.object({callId:id,department:z.enum(deps),summary:str,consent:z.boolean()}).parse(p);return handoff(b.callId,b.department,b.summary,b.consent,actor);}
 case 'knowledge.save':{admin();const f=factSchema.parse(p.fact),key=f.id??uid();await db.prepare('INSERT INTO knowledge (id,title,department,topic,question,answer,answer_te,answer_hi,source,status,access,effective_from,expires_on,approved_by,approved_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,\'draft\',?,?,?,NULL,NULL,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,department=excluded.department,topic=excluded.topic,question=excluded.question,answer=excluded.answer,answer_te=excluded.answer_te,answer_hi=excluded.answer_hi,source=excluded.source,status=\'draft\',access=excluded.access,effective_from=excluded.effective_from,expires_on=excluded.expires_on,approved_by=NULL,approved_at=NULL,updated_at=excluded.updated_at').bind(key,f.title,f.department,f.topic,f.question,f.answer,f.answerTe,f.answerHi,f.source,f.access,f.effectiveFrom,f.expiresOn,now()).run();await log(actor,'knowledge.draft_saved',key,f.title);return {id:key};}
 case 'knowledge.approve':case 'knowledge.withdraw':{admin();const b=z.object({id}).parse(p);const f=(await facts()).find(f=>f.id===b.id);if(!f)throw new Error('Source not found');if(p.action==='knowledge.approve'&&(!crisp(f.answer)||f.expiresOn<now().slice(0,10)))throw new Error('Source is expired or the answer is too long');if(p.action==='knowledge.approve'&&f.source.startsWith('document:')){const documentId=f.source.match(/^document:([0-9a-f-]+)#section:\d+$/)?.[1];const document=await db.prepare('SELECT status,effective_from,expires_on FROM college_documents WHERE id=?').bind(documentId??'').first<any>();if(!document||document.status!=='active'||f.effectiveFrom<document.effective_from||f.expiresOn>document.expires_on)throw new Error('The linked document is withdrawn or the answer dates exceed its validity');}const status=p.action==='knowledge.approve'?'approved':'withdrawn';await db.prepare('UPDATE knowledge SET status=?,approved_by=?,approved_at=?,updated_at=? WHERE id=?').bind(status,status==='approved'?actor:null,status==='approved'?now():null,now(),b.id).run();await log(actor,`knowledge.${status}`,b.id,f.title);return {ok:true};}
 case 'department.save':{admin();const b=z.object({id:z.enum(deps),target:z.string().max(200).refine(x=>!x||/^tel:\+\d{8,15}$|^sip:[A-Za-z0-9_.+-]+@[A-Za-z0-9.-]+$/.test(x),'Use a tel:+country-number or SIP address'),hours:z.string().regex(/^\d\d:\d\d[–-]\d\d:\d\d$/).refine(x=>{const m=x.split(/[–-]/);return m[0]<m[1]&&m.every(t=>Number(t.slice(0,2))<24&&Number(t.slice(3))<60)},'Use valid increasing hours'),days:z.string().regex(/^[0-6](,[0-6])*$/),enabled:z.boolean()}).parse(p);if(b.enabled&&!b.target)throw new Error('A destination is required');await db.prepare('UPDATE departments SET target=?,hours=?,days=?,enabled=? WHERE id=?').bind(b.target,b.hours,b.days,b.enabled?1:0,b.id).run();await log(actor,'department.updated',b.id,b.enabled?'enabled':'disabled');return {ok:true};}
 case 'ticket.create':{const b=z.object({department:z.enum(deps),summary:str,category:z.enum(['callback','complaint','support']),contact:z.string().max(200).default(''),callbackAt:z.string().datetime().nullable().default(null),callId:id.nullable().default(null)}).parse(p);if(b.callId)await loadCall(b.callId);const key=await ticket(b.callId,b.department,b.summary,b.category,b.contact,b.callbackAt);await log(actor,'ticket.created',key,b.category);return {id:key};}
 case 'ticket.update':{admin();const b=z.object({id,status:z.enum(['open','in_progress','resolved'])}).parse(p);await db.prepare('UPDATE tickets SET status=?,updated_at=? WHERE id=?').bind(b.status,now(),b.id).run();await log(actor,'ticket.updated',b.id,b.status);return {ok:true};}
 case 'config.save':{admin();const b=z.object({collegeName:str,retentionDays:z.number().int().min(1).max(365),recordingEnabled:z.boolean(),voiceEnabled:z.boolean()}).parse(p);await db.prepare('UPDATE settings SET value=? WHERE id=\'config\'').bind(JSON.stringify({...await config(),...b})).run();await log(actor,'config.updated','config','College settings');return {ok:true};}
 case 'evaluate':{admin();const r=runEvaluation();const key=uid();await db.prepare('INSERT INTO evaluations (id,created_at,passed,total,results) VALUES (?,?,?,?,?)').bind(key,now(),r.passed,r.total,JSON.stringify(r.results)).run();await log(actor,'evaluation.completed',key,`${r.passed}/${r.total}`);return r;}
 case 'retention.purge':{admin();const cfg=await config(),before=new Date(Date.now()-cfg.retentionDays*86400000).toISOString();const stale=(await db.prepare('SELECT id,recording_key FROM calls WHERE ended_at IS NOT NULL AND ended_at<?').bind(before).all()).results;
 for(const c of stale){if(c.recording_key&&runtime().RECORDINGS)await runtime().RECORDINGS!.delete(String(c.recording_key));await db.batch([db.prepare('DELETE FROM turns WHERE call_id=?').bind(c.id),db.prepare('DELETE FROM verifications WHERE call_id=?').bind(c.id),db.prepare('DELETE FROM messages WHERE call_id=?').bind(c.id),db.prepare('UPDATE email_outbox SET call_id=NULL WHERE call_id=?').bind(c.id),db.prepare('UPDATE tickets SET call_id=NULL WHERE call_id=?').bind(c.id),db.prepare('DELETE FROM calls WHERE id=?').bind(c.id)]);}await db.prepare("DELETE FROM email_outbox WHERE created_at<? AND status NOT IN ('sending','uncertain')").bind(before).run();await log(actor,'retention.purged','calls',`${stale.length} calls removed`);return {removed:stale.length};}
 default:throw new Error('Unknown action');
 }
}
