import { sqliteTable, text, integer, index } from 'drizzle-orm/sqlite-core';
export const settings = sqliteTable('settings',{id:text('id').primaryKey(), value:text('value').notNull()});
export const knowledge = sqliteTable('knowledge',{
 id:text('id').primaryKey(), title:text('title').notNull(), department:text('department').notNull(), topic:text('topic').notNull(),
 question:text('question').notNull(), answer:text('answer').notNull(), answerTe:text('answer_te').notNull().default(''), answerHi:text('answer_hi').notNull().default(''),
 source:text('source').notNull(), status:text('status').notNull().default('draft'), access:text('access').notNull().default('public'),
 effectiveFrom:text('effective_from').notNull(), expiresOn:text('expires_on').notNull(), approvedBy:text('approved_by'), approvedAt:text('approved_at'), updatedAt:text('updated_at').notNull(),
}, t=>[index('idx_knowledge_topic_status').on(t.topic,t.status)]);
export const departments=sqliteTable('departments',{id:text('id').primaryKey(), name:text('name').notNull(), target:text('target').notNull().default(''), hours:text('hours').notNull().default('09:00–17:00'), days:text('days').notNull().default('1,2,3,4,5'), enabled:integer('enabled').notNull().default(0)});
export const calls=sqliteTable('calls',{id:text('id').primaryKey(), channel:text('channel').notNull(), language:text('language').notNull().default('en'), status:text('status').notNull().default('active'), department:text('department').notNull().default('general'), startedAt:text('started_at').notNull(), endedAt:text('ended_at'), consent:integer('consent').notNull().default(0), feedback:integer('feedback'), reviewStatus:text('review_status').notNull().default('unreviewed'), reviewNote:text('review_note').notNull().default(''), recordingKey:text('recording_key'), summary:text('summary').notNull().default('')},t=>[index('idx_calls_started').on(t.startedAt)]);
export const turns=sqliteTable('turns',{id:text('id').primaryKey(), callId:text('call_id').notNull().references(()=>calls.id), role:text('role').notNull(), text:text('text').notNull(), decision:text('decision'), sourceIds:text('source_ids').notNull().default('[]'), latencyMs:integer('latency_ms').notNull().default(0), createdAt:text('created_at').notNull()},t=>[index('idx_turns_call').on(t.callId)]);
export const tickets=sqliteTable('tickets',{id:text('id').primaryKey(), callId:text('call_id').references(()=>calls.id), department:text('department').notNull(), category:text('category').notNull(), summary:text('summary').notNull(), status:text('status').notNull().default('open'), createdAt:text('created_at').notNull(), updatedAt:text('updated_at').notNull(), callbackAt:text('callback_at'), contact:text('contact').notNull().default(''), priority:text('priority').notNull().default('normal')},t=>[index('idx_tickets_status').on(t.status)]);
export const audit=sqliteTable('audit',{id:text('id').primaryKey(), actor:text('actor').notNull(), action:text('action').notNull(), entityId:text('entity_id').notNull(), detail:text('detail').notNull(), createdAt:text('created_at').notNull()});
export const evaluations=sqliteTable('evaluations',{id:text('id').primaryKey(), createdAt:text('created_at').notNull(), passed:integer('passed').notNull(), total:integer('total').notNull(), results:text('results').notNull()});
export const events=sqliteTable('events',{id:text('id').primaryKey(), result:text('result').notNull().default('processing'), createdAt:text('created_at').notNull()});
export const voiceBudgets=sqliteTable('voice_budgets',{id:text('id').primaryKey(),uses:integer('uses').notNull().default(1),expiresAt:text('expires_at').notNull()},t=>[index('idx_voice_budgets_expiry').on(t.expiresAt)]);
export const verifications=sqliteTable('verifications',{callId:text('call_id').primaryKey().references(()=>calls.id),challenge:text('challenge').notNull(),expiresAt:text('expires_at').notNull(),verifiedAt:text('verified_at')});
export const messages=sqliteTable('messages',{id:text('id').primaryKey(),callId:text('call_id').notNull().references(()=>calls.id),sourceId:text('source_id').notNull(),channel:text('channel').notNull(),status:text('status').notNull(),createdAt:text('created_at').notNull()});
export const emailDirectory=sqliteTable('email_directory',{id:text('id').primaryKey(),recipientName:text('recipient_name').notNull().default(''),email:text('email').notNull().default(''),source:text('source').notNull().default(''),verifiedBy:text('verified_by'),verifiedAt:text('verified_at'),verifiedUntil:text('verified_until'),updatedAt:text('updated_at').notNull()});
export const emailOutbox=sqliteTable('email_outbox',{id:text('id').primaryKey(),requestId:text('request_id').notNull().unique(),callId:text('call_id').references(()=>calls.id),department:text('department').notNull(),recipient:text('recipient').notNull().default(''),recipientName:text('recipient_name').notNull().default(''),subject:text('subject').notNull(),body:text('body').notNull(),replyTo:text('reply_to').notNull().default(''),consent:integer('consent').notNull().default(0),status:text('status').notNull().default('draft'),detail:text('detail').notNull().default(''),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),sentAt:text('sent_at'),reviewedBy:text('reviewed_by'),reviewedAt:text('reviewed_at'),recipientVerifiedAt:text('recipient_verified_at')},t=>[index('idx_email_status').on(t.status)]);
